let
    Origen = Excel.CurrentWorkbook(){[Name="TVentas_Raw"]}[Content],
    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"VentaID", Int64.Type}, {"Fecha", type text}, {"ProductoID", type text}, {"ClienteID", type text}, {"Canal", type text}, {"Cantidad", Int64.Type}, {"Precio_Unitario", type text}, {"Descuento", type text}, {"Vendedor", type text}, {"Sucursal", type text}, {"Observacion", type text}}),
    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado", "Fecha_Normalizada", each let
    txt = Text.Trim([Fecha]),
    normalizada = Text.Replace(Text.Replace(txt,".","-"),"/","-"),
    partes = Text.Split(normalizada,"-")
in
    if Text.Length(partes{0}) = 4 then
        #date(
            Number.FromText(partes{0}),
            Number.FromText(partes{1}),
            Number.FromText(partes{2})
        )
    else
        #date(
            Number.FromText(partes{2}),
            Number.FromText(partes{1}),
            Number.FromText(partes{0})
        )),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Fecha_Normalizada", type date}}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado1",{"Fecha"}),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Columnas quitadas",{"VentaID", "Fecha_Normalizada", "ProductoID", "ClienteID", "Canal", "Cantidad", "Precio_Unitario", "Descuento", "Vendedor", "Sucursal", "Observacion"}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"Fecha_Normalizada", "Fecha"}}),
    #"Texto en mayúsculas" = Table.TransformColumns(#"Columnas con nombre cambiado",{{"ProductoID", Text.Upper, type text}}),
    #"Valor reemplazado" = Table.ReplaceValue(#"Texto en mayúsculas"," ","",Replacer.ReplaceText,{"ProductoID"}),
    #"Texto en mayúsculas1" = Table.TransformColumns(#"Valor reemplazado",{{"ClienteID", Text.Upper, type text}}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Texto en mayúsculas1"," ","",Replacer.ReplaceText,{"ClienteID"}),
    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Valor reemplazado1",{{"Canal", Text.Proper, type text}}),
    Personalizado1 = Table.TransformColumns(
    #"Poner En Mayúsculas Cada Palabra",
    {
        {"Cantidad",
        each if Value.Is(_, Number.Type) and _ > 0 then _ else null,
        Int64.Type}
    }
),
    #"Personalizada agregada3" = Table.AddColumn(Personalizado1, "Precio_Limpio", each let txt = Text.Trim([Precio_Unitario]), posComa = Text.PositionOf(txt, ",", Occurrence.Last), posPunto = Text.PositionOf(txt, ".", Occurrence.Last), len = Text.Length(txt), limpio = if posComa <> -1 and posPunto <> -1 then if posComa > posPunto then Text.Replace(txt, ".", "") else Text.Replace(Text.Replace(txt, ",", ""), ".", ",") else if posComa <> -1 then if len - posComa - 1 = 3 then Text.Replace(txt, ",", "") else txt else if posPunto <> -1 then if len - posPunto - 1 = 3 then Text.Replace(txt, ".", "") else Text.Replace(txt, ".", ",") else txt in limpio),
    #"Columnas reordenadas1" = Table.ReorderColumns(#"Personalizada agregada3",{"VentaID", "Fecha", "ProductoID", "ClienteID", "Canal", "Cantidad", "Precio_Unitario", "Precio_Limpio", "Descuento", "Vendedor", "Sucursal", "Observacion"}),
    #"Filas filtradas" = Table.SelectRows(#"Columnas reordenadas1", each ([Precio_Limpio] <> "abc")),
    #"Columnas quitadas1" = Table.RemoveColumns(#"Filas filtradas",{"Precio_Unitario"}),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columnas quitadas1",{{"Precio_Limpio", "Precio_Unitario"}}),
    #"Valor reemplazado4" = Table.ReplaceValue(#"Columnas con nombre cambiado1",".",",",Replacer.ReplaceText,{"Descuento"}),
    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","abc","0",Replacer.ReplaceText,{"Descuento"}),
    Personalizado3 = Table.TransformColumns(
    #"Valor reemplazado5",
    {
        {"Descuento",
        each
            let
                valorOriginal = _
            in
                if valorOriginal = null then
                    null
                else
                    let
                        txt = Text.Trim(Text.From(valorOriginal)),
                        valor =
                            if txt = "" then
                                null
                            else if Text.Contains(txt,"%") then
                                try Number.From(Text.Replace(Text.Replace(txt,"%","")," ","")) / 100 otherwise null
                            else
                                try Number.From(txt) otherwise null
                    in
                        if valor <> null and valor >= 0 and valor <= 0.5
                        then valor
                        else null,
        type nullable number}
    }
),
    #"Filas filtradas1" = Table.SelectRows(Personalizado3, each ([Descuento] <> null) and ([Cantidad] <> null)),
    #"Duplicados quitados" = Table.Distinct(#"Filas filtradas1", {"VentaID"}),
    #"Poner En Mayúsculas Cada Palabra1" = Table.TransformColumns(#"Duplicados quitados",{{"Vendedor", Text.Proper, type text}}),
    #"Valor reemplazado2" = Table.ReplaceValue(#"Poner En Mayúsculas Cada Palabra1"," ","",Replacer.ReplaceText,{"Vendedor"}),
    #"Poner En Mayúsculas Cada Palabra2" = Table.TransformColumns(#"Valor reemplazado2",{{"Sucursal", Text.Proper, type text}}),
    #"Valor reemplazado3" = Table.ReplaceValue(#"Poner En Mayúsculas Cada Palabra2"," ","",Replacer.ReplaceText,{"Sucursal"}),
    #"Poner En Mayúsculas Cada Palabra3" = Table.TransformColumns(#"Valor reemplazado3",{{"Observacion", Text.Proper, type text}}),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Poner En Mayúsculas Cada Palabra3",{{"Precio_Unitario", type number}}),
    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado2", "Total_Bruto", each [Cantidad]*[Precio_Unitario]),
    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Personalizada agregada1",{{"Total_Bruto", type number}}),
    #"Personalizada agregada2" = Table.AddColumn(#"Tipo cambiado3", "Total_Neto", each [Cantidad]*[Precio_Unitario]*1-[Descuento])
in
    #"Personalizada agregada2"
